path:
  raw_path: "raw/20260611/TSL-TCM-JTNP-Ⅲ20260611101348556.xlsx"
  pd_path: "raw/20260611/TSL-CM-JSSPMFSL-III-酒石酸匹莫范色林胶囊III期-方案偏离-20260129.xlsx"
  code_path: "raw/20260611/TSL-CM-JSSPMFSL-III-酒石酸匹莫范色林胶囊III期-医学编码报告-20260127.xlsx"
  remark_path: "raw/20260611/备注明细_20260129091658_3008.xlsx"
  timewin_path: "raw/time window.xlsx"
  output_path: "output/20260611"
